version: '2'
services:
  app:
    image: app
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo/src-dev
    ports:
      - 10000:8080
  mongo:
    image: mongo:3.4.2
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
volumes:
  mongo-data:
  mongo-config:
